### ISSUE TITLE
Can not have two parallel Polestar IDs anymore

### ISSUE THREAD

**Issue by magnushacker** [pypolestar/polestar_api#182] opened 2024-10-24 14:41 UTC
I have two cars and two separate polestar IDs. Until 1.7.2 this worked fine but in 1.7.3 the second car is no longer available.

![image](https://github.com/user-attachments/assets/7c320e06-8262-47d3-bd34-b01dc522b3e2)

![image](https://github.com/user-attachments/assets/8afb511f-a304-4419-b4b4-0806148a41ef)

I can see that the integration can successfully authenticate with the first entry (tried to anonymize the logs a bit):

```
2024-10-24 16:25:02.083 DEBUG (MainThread) [custom_components.polestar_api] async_setup_entry: <ConfigEntry entry_id=79a8864e79aa908b1b02d47ca4cb1dff version=1 domain=polestar_api title=Magnus Polestar state=ConfigEntryState.SETUP_IN_PROGRESS unique_id=None>
<....>
2024-10-24 16:25:03.401 DEBUG (MainThread) [custom_components.polestar_api.pypolestar.auth] {'data': {'getAuthToken': {'id_token': None, 'access_token': 'eyJhbGciOiJSUzI1NiIsImtpZCI6IlVVdkRibjM5QkZkcklhUWR0ZXhFVHdfYkxEa19SUzI1NiIsInBpLmF0bSI6ImwifQ.eyJzY29wZSI6IiIsImNsa
<......>
2024-10-24 16:25:05.053 DEBUG (MainThread) [custom_components.polestar_api.pypolestar.polestar] {'data': {'getConsumerCarsV2': [{'vin': 'XXX', 'internalVehicleIdentifier': XXX, 'salesType': '82B', 'currentPlannedDeliveryDate': '2021-05-27', 'market': 'SE', 'originalMarket': 'SE', 'pno34': 'XXX', 'modelYear': '2021', 'registrationNo': 'TBA97R', 

```

but then it seems to reuse the same authentication for the second car and of course gets the same API response back:

```
2024-10-24 16:25:10.963 DEBUG (MainThread) [custom_components.polestar_api] async_setup_entry: <ConfigEntry entry_id=90f0c8caa13aa5f0c56c2bcd2f2392ba version=1 domain=polestar_api title=Emma Polestar state=ConfigEntryState.SETUP_IN_PROGRESS unique_id=None>
<....>
2024-10-24 16:25:11.480 DEBUG (MainThread) [custom_components.polestar_api.pypolestar.auth] {'data': {'getAuthToken': {'id_token': None, 'access_token': 'eyJhbGciOiJSUzI1NiIsImtpZCI6IlVVdkRibjM5QkZkcklhUWR0ZXhFVHdfYkxEa19SUzI1NiIsInBpLmF0bSI6ImwifQ.eyJzY29wZSI6IiIsImNsa
<......>
2024-10-24 16:25:12.473 DEBUG (MainThread) [custom_components.polestar_api.pypolestar.polestar] {'data': {'getConsumerCarsV2': [{'vin': 'XXX', 'internalVehicleIdentifier': XXX', 'salesType': '82B', 'currentPlannedDeliveryDate': '2021-05-27', 'market': 'SE', 'originalMarket': 'SE', 'pno34': 'XXX', 'modelYear': '2021', 'registrationNo': 'TBA97R', 
```

**Comment by jschlyter** [comment] 2024-10-24 18:10
Do you have access to each others cars?

**Comment by leeyuentuen** [comment] 2024-10-24 20:30
Should work before on old version: 
https://github.com/pypolestar/polestar_api/issues/150

**Comment by magnushacker** [comment] 2024-10-25 11:01
I deleted both integration entries and re-added one of them. Only one of the cars show up and when I try to add the second entry using the other polestar ID, it fails and cannot generate devices and sensors. Doesn't matter which one I start with.

I then downgraded to 1.7.2 and experience the same thing. 

If I downgrade to 1.6.15, I do get both cars displayed as two devices under the same integration entry.

**Comment by jschlyter** [comment] 2024-10-25 11:33
The challenge is most likely that both devices see both cars and there's nothing telling any of them which one to ignore?

**Comment by magnushacker** [comment] 2024-10-26 22:26
I now deleted everything, restarted HA, and then installed the latest 1.7.3 version of the integration. 

When I add the first entry using my polestar ID, only one car shows up. In the polestar app I see both. 

When I add the second entry using the other polestar ID, it fails to create devices and sensors due to duplicate IDs. 

Couldn't this mean that the api does indeed provide information on both cars, but that the integration only picks up the first of them?

**Comment by jschlyter** [comment] 2024-10-27 11:01
I agree and believe the integration does not work as intended with multiple cars. Moving this to https://github.com/pypolestar/polestar_api/discussions/185 for further discussion and we'll circle back here later.

**Comment by jschlyter** [comment] 2024-10-30 07:55
https://github.com/pypolestar/polestar_api/releases/tag/1.8.0b1 now published (pre-release),please test

**Comment by jschlyter** [comment] 2024-10-30 21:27
Can you provide me with some more debug logs adding 1st car, then the other (both with VIN). You should be able to turn on debugging with the following action:

```
action: logger.set_level
data:
  custom_components.polestar_api: debug
```

You can email me the logs (see github profile for address).

**Comment by jschlyter** [comment] 2024-11-01 11:34
I've done some additional work in #191 and I can now even add two copies of the same car. I have not yet tried with two different Polestar IDs and need some more help testing that.

**Comment by jschlyter** [comment] 2024-11-12 09:28
Just tried as a guest of another Polestar, but as it does not show up in the API I cannot debug it :-(

**Comment by magnushacker** [comment] 2024-11-12 10:36
I am now using two instances in parallel and can now see both our cars in the family. Each ID only displays one car (we are both admins in both cars).

**Comment by magnushacker** [comment] 2024-11-18 21:05
Yes, it works fine for my use case where we have two separate owner
accounts, one for each car. If we buy a third one I will test what happens
when one owner owns two cars ;)


mån 18 nov. 2024 kl. 21:32 skrev Jakob Schlyter ***@***.***>:

**Closed** 2024-11-18 21:16 UTC
Labels: bug
